language: node_js
node_js:
  - "4"
  - "6"
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - echo "Running Linter..."
  - npm run lint
  - echo "Running Tests..."
  - npm test