language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - echo "Running Linter..."
  - npm run lint
  - echo "Running Tests..."
  - npm test
